{% set name = "edgartools" %}
{% set version = "4.26.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/edgartools-{{ version }}.tar.gz
  sha256: 639626e0eb964f8b2f85600c87c681d8261b1b7bd20294b7a5b8319c910b0916

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.26.3
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.25.0
    - pandas >=2.0.0
    - tabulate >=0.9.0
    - pyarrow >=17.0.0
    - beautifulsoup4 >=4.10.0
    - lxml >=4.4
    - rich >=13.8.0
    - humanize >=4.0.0
    - stamina >=24.2.0
    - orjson >=3.6.0
    - textdistance >=4.5.0
    - rank-bm25 >=0.2.1
    - rapidfuzz >=3.5.0
    - unidecode >=1.2.0
    - pydantic >=2.0.0
    - tqdm >=4.62.0
    - nest-asyncio >=1.5.1
    - jinja2 >=3.1.0
    - httpxthrottlecache >=0.1.6

test:
  imports:
    - edgar
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Navigate Edgar filings with ease
  home: https://github.com/dgunning/edgartools
  dev_url: https://github.com/dgunning/edgartools
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - faceprint
